services:
  db:
    image: postgres:16.3
    container_name: postgress_db
    environment:
      POSTGRES_DB: socialnetwork
      POSTGRES_USER: user
      POSTGRES_PASSWORD: adminpassword
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
  redis:
    image: redis:6.2-alpine
    container_name: social-redis
    command: ["redis-server", "--loglevel", "warning"]
    ports:
      - "6379:6379"
    restart: unless-stopped

volumes:
  db-data: